# Generated by Django 3.1.11 on 2022-03-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Createtodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField()),
                ('important', models.BooleanField(default=False)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
