# Generated by Django 3.1.11 on 2022-03-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserInformation',
        ),
    ]
